# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_COM_S(object):
    def setupUi(self, COM_S):
        COM_S.setObjectName("COM_S")
        COM_S.resize(976, 692)
        self.centralwidget = QtWidgets.QWidget(COM_S)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setMinimumSize(QtCore.QSize(831, 450))
        self.frame_1.setMaximumSize(QtCore.QSize(831, 450))
        self.frame_1.setStyleSheet("background-color: rgb(119,215,226);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GRPH_1 = QtWidgets.QVBoxLayout()
        self.GRPH_1.setObjectName("GRPH_1")
        self.horizontalLayout.addLayout(self.GRPH_1)
        self.horizontalLayout_3.addWidget(self.frame_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.BTN_CONECTAR = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_CONECTAR.setObjectName("BTN_CONECTAR")
        self.horizontalLayout_2.addWidget(self.BTN_CONECTAR)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.BTN_DESCONECTAR = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_DESCONECTAR.setObjectName("BTN_DESCONECTAR")
        self.horizontalLayout_2.addWidget(self.BTN_DESCONECTAR)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        COM_S.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(COM_S)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 26))
        self.menubar.setObjectName("menubar")
        COM_S.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(COM_S)
        self.statusbar.setObjectName("statusbar")
        COM_S.setStatusBar(self.statusbar)

        self.retranslateUi(COM_S)
        QtCore.QMetaObject.connectSlotsByName(COM_S)

    def retranslateUi(self, COM_S):
        _translate = QtCore.QCoreApplication.translate
        COM_S.setWindowTitle(_translate("COM_S", "MainWindow"))
        self.BTN_CONECTAR.setText(_translate("COM_S", "Conectar"))
        self.BTN_DESCONECTAR.setText(_translate("COM_S", "Desconectar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    COM_S = QtWidgets.QMainWindow()
    ui = Ui_COM_S()
    ui.setupUi(COM_S)
    COM_S.show()
    sys.exit(app.exec_())
